### ISSUE TITLE
Unfiled arrow for access relationships

### ISSUE THREAD

**Issue by ricardoamaro** [plantuml-stdlib/Archimate-PlantUML#12]
First thank you so much for this piece of software!

Second I have a small question regarding the access arrow.
How do I actually use Rel_Access and specify the directions?

5.2.2 Access Relationship in
https://pubs.opengroup.org/architecture/archimate3-doc/chap05.html

Thank you

**Comment by ricardoamaro** [comment]
Ok, I just noticed:

https://github.com/ebbypeter/Archimate-PlantUML/blob/4be42bee55360419a023d0af4a9f9d5c37ee7aed/Archimate.puml#L250

But that is still not giving an unfiled arrow.
An way we could solve that?

**Comment by Potherca** [comment]
@ricardoamaro Are you still having issues with this? If so, could you post your diagrams, so I can take a look?

**Comment by Potherca** [comment]
Closing due to lack of response. If this is still an problem (or if the problem returns) this issue will be re-opened.
