### ISSUE TITLE
Join https://github.com/plantuml-stdlib and/or migrate there?

### ISSUE THREAD

**Issue by Potherca** [plantuml-stdlib/Archimate-PlantUML#29]
Several of us have been making an effort to bring together the projects and people who feed sprites into the official [plantuml-stdlib](https://github.com/plantuml/plantuml-stdlib/).

We've been doing this under https://github.com/plantuml-stdlib/, with the go-ahead of Arnaud Roques (creator of PlantUML)

This ticket is to ask whether you would be interested in joining that effort and/or migrating this project to the PlantUML-StdLib organization.

The main reason for asking is to see if, by joining forces, we can make sure that any sprites already added to the official plantuml-stdlib remain maintained.

So, what do you think?

**Comment by ebbypeter** [comment]
Hi,

I am interested in this.  I feel it will be good for the community to join forces.
Let me know the next steps.

Regards,
Ebby Peter
________________________________

**Comment by Potherca** [comment]
I've sent you an invitation to join [the plantuml-stdlib org](https://github.com/plantuml-stdlib). Welcome on board!

Once you have accepted, you can [migrate this repository to the `plantuml-stdlib` org](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account).

Any links in the code or docs here will need to be updated to the repository's new home.
If you do not have the time or energy to change the links, I can do that for you, just let me know.

At a later point (once we've got answers from more maintainers) the `INFO` files in [the upstream repo](https://github.com/plantuml/plantuml-stdlib/) will also be updated to reflect these changes. 

But for now, that's all!

**Comment by ebbypeter** [comment]
Completed the migration. I have some enhancements planned which I will incorporate later.

**Comment by Potherca** [comment]
Awesome! Looking forward to the future :smiley:
