### ISSUE TITLE
Non standart Assignment relation looking

### ISSUE THREAD

**Issue by dseverov** [plantuml-stdlib/Archimate-PlantUML#33]
Does it possible to make Assignment relation looking closer to Archimate Standart - with black and smaller circle at starting end ?

Archimate PlantUML looking
<img width="335" alt="Archimate-PlantUML" src="https://user-images.githubusercontent.com/3100700/116209948-1284a200-a74b-11eb-8b7d-9b8277969a95.png">
Archimate Standart looking
<img width="365" alt="Archimate-Standart" src="https://user-images.githubusercontent.com/3100700/116209950-13b5cf00-a74b-11eb-9f30-e7076680de00.png">

(source: https://pubs.opengroup.org/architecture/archimate3-doc/chap05.html#_Toc10045314)

**Comment by Potherca** [comment]
It looks like this is caused by using `0-->>` as arrow notation, which gives  an open circle.

If it is replaced with `@-->>`, we get the desired result.

I've opened #35 to resolve this.
