### ISSUE TITLE
"realisation" sprite name instead of "realization"

### ISSUE THREAD

**Issue by dseverov** [plantuml-stdlib/Archimate-PlantUML#34]
relation name standart spelling is **realization** in macro name is **Rel_Realization** too
<img width="367" alt="std" src="https://user-images.githubusercontent.com/3100700/116306286-8ce60e00-a7ad-11eb-97db-38181c81c972.png">

but sprite name is **realisation** 
<img width="151" alt="sprite" src="https://user-images.githubusercontent.com/3100700/116306310-940d1c00-a7ad-11eb-9c5e-af6fd03a4c67.png">

Sprite name seems need to be standart too. Is not it?

**Comment by Potherca** [comment]
The sprite name comes from the main PlantUML repo (see https://github.com/plantuml/plantuml/blob/master/src/sprites/archimate/realisation.png). If things are to be resolved, the sprite in the main repo would need be renamed.

Closing this issue, as we cannot fix it here.
