### ISSUE TITLE
stdLib references non existing url (...ebbypeter...)

### ISSUE THREAD

**Issue by kirchsth** [plantuml-stdlib/Archimate-PlantUML#36]
Hi @Potherca,

if  all integrated stdlibs are requested, `Archimate-PlantUML` references the moved "https://github.com/ebbypeter/Archimate-PlantUML" and the version is 0.0.1.

```
@startuml
stdlib
@enduml
```

![](http://www.plantuml.com/plantuml/png/SoWkIImgAStDuIekISd9JE9oICrB0N81)

Best regards
Helmut

PS.: It could be that other urls should be updated too

**Comment by Potherca** [comment]
Those are taken from the `INFO` files in https://github.com/plantuml/plantuml-stdlib/. I'll go through them to make sure the URLs are all up to date. :+1:

**Comment by Potherca** [comment]
Opened https://github.com/plantuml/plantuml-stdlib/pull/43 to resolve this. Closing this issue.

Thanks again for pointing this out!
