### ISSUE TITLE
Minor request - flat Technology_Node

### ISSUE THREAD

**Issue by kwanlowe** [plantuml-stdlib/Archimate-PlantUML#37]
Thanks for an eminently useful package.  I have a small request:

For the Technology_Service, possible to add a "flat" version of the node graphic?
E.g.:
```
!define Technology_Node_f(e_alias, e_label) rectangle #TECHNOLOGY "e_label" <<$archimate/technology-node>> as e_alias
```

This will allow similar look to diagrams created with Archi.

**Comment by Potherca** [comment]
Thank you for the compliment!

Regarding a "flat" version, I'm not sure this is something we would want to support.

One reason is that Archimate-PlantUML doesn't attempt to emulate the look of others tools. It just offers a PlantUML based implementation.
Another reason is that, as you've already found, it is trivial for users to change existing (or add new) shapes.
 
From this perspective, adding a flat look for a single doesn't seem to add much value...

**Comment by kwanlowe** [comment]
Ahh, I understand. Thanks so much for the response.
