### ISSUE TITLE
Nested Group of Archimate Component

### ISSUE THREAD

**Issue by rijdz** [plantuml-stdlib/Archimate-PlantUML#38]
Hey can we have grouping by Archimate Component?

Let's say I have requirement to create catalog of many Business Services. Each Business Services consist of many Business Process.

**Comment by Potherca** [comment]
Hi! I am not entire sure I understand what you are asking.

Could you post an example of what you have tried, or what you expect to happen?

**Comment by rijdz** [comment]
I think I solved it but I forgot to post it here

This is the result for what the nested catalog that I need.

![sample](https://user-images.githubusercontent.com/14847120/151764493-f168a9e5-0c42-4d85-829a-cee455440ad4.png)


And here is the code
```
@startuml
skinparam roundcorner 25
skinparam defaultTextAlignment center
skinparam wrapWidth 400
skinparam maxMessageSize 150
skinparam StereotypeAlignment right
left to right direction
title Core Business Services

rectangle "Strategic" <<$archimate/business-function>> #Business{
    rectangle "Corporate Strategic Planning"  <<$archimate/business-service>>#Business{
        rectangle "Strategic Intent"  <<$archimate/business-process>>#Business 
        rectangle "Ext. and Int. Analysis"  <<$archimate/business-process>>#Business 
        rectangle "Strategy and Roadmap"  <<$archimate/business-process>>#Business 
        rectangle "Initiatives & Timeline"  <<$archimate/business-process>>#Business 
        rectangle "Financial Projection"  <<$archimate/business-process>>#Business 
    }
}

@enduml
```

**Comment by The-Lum** [comment]
Hi @rijdz, @Potherca, @tvolin and all,

FYI here is a _[new]_ wanted feature on `plantuml core` in order to allow _'Nested Group of Archimate Component'_:
- https://github.com/plantuml/plantuml/issues/1818

Regards,
Th.

**Comment by The-Lum** [comment]
Hello @rijdz, @Potherca, @ebbypeter,

With the fix of:
- plantuml/plantuml#1818

and the new functionality of nestable `archimate` element, with [last snapshot beta](https://github.com/plantuml/plantuml/releases/tag/snapshot) _(and on next release 1.2025.3)_, we can have:
```puml
@startuml
!include <archimate/Archimate>

title Core Business Service

Business_Function(s, "Strategic") {
  Business_Service(csp, Corporate Strategic Planning") {
    Business_Process(si, "Strategic Intent")
    Business_Process(eaia, "Ext. and Int. Analysis" )
    Business_Process(sar, "Strategy and Roadmap")
    Business_Process(iat, "Initiatives & Timeline")
    Business_Process(fp, "Financial Projection")
  }
}
@enduml
```
>[![](https://img.plantuml.biz/plantuml/svg/TP71IiD048RlWRp3651IAAbMUXDf5Gkz5UkzZ9jf7TdCXjr9i8ZlxgQQjfV0mWwptpS3_yw3ejUcicbonM9iKn8ye3SVNA7IPD5NZscI9ifg2PwT9tXg0Wk501loBHlgdllUTjc8KNQIXp5a6_NHtxF9Hl2T9d1Ij_zgRa8zxgRMhYFX9C3QeWZBlZSltBLt9jvvuCiLi18bqMmqG1CoHlxbImj0AJkyW8MWFGGE6Gnf0Vrvo-5elZeiAwm7Dp5gL5R26YjkAS0Dl755DcA3qYxca2rPK0oZXTZ-f6EGVyPFciIpSqx9mrqnlPtEYljtKfp11AvRyg7BFA9paZ9-wIy0)](https://editor.plantuml.com/uml/TP71IiD048RlWRp3651IAAbMUXDf5Gkz5UkzZ9jf7TdCXjr9i8ZlxgQQjfV0mWwptpS3_yw3ejUcicbonM9iKn8ye3SVNA7IPD5NZscI9ifg2PwT9tXg0Wk501loBHlgdllUTjc8KNQIXp5a6_NHtxF9Hl2T9d1Ij_zgRa8zxgRMhYFX9C3QeWZBlZSltBLt9jvvuCiLi18bqMmqG1CoHlxbImj0AJkyW8MWFGGE6Gnf0Vrvo-5elZeiAwm7Dp5gL5R26YjkAS0Dl755DcA3qYxca2rPK0oZXTZ-f6EGVyPFciIpSqx9mrqnlPtEYljtKfp11AvRyg7BFA9paZ9-wIy0)

_Enjoy,_
Regards,
Th.
