### ISSUE TITLE
$BUSINESS_FILLCOLOR missing made nesting Business_Service incorrect

### ISSUE THREAD

**Issue by jmanteau** [plantuml-stdlib/Archimate-PlantUML#47]
https://github.com/plantuml-stdlib/Archimate-PlantUML/blob/97003f77e1f584a30293d31a6195f279165b4544/Archimate.puml#L231

This line
```
    rectangle "$label" <<$archimate/business-service>> as $alias 
```
needs to be transformed in

```
    rectangle "$label" <<$archimate/business-service>> as $alias $BUSINESS_FILLCOLOR
```

Then this diagram is working as expected:
```
@startuml

!includeurl Archimate.puml

Business_Product(psl01, "Private and Public Cloud", true) {
    Business_Service(container, "Container", true){
        Application_Component(Software_Component_E, "Software Component E")
    }

    Business_Service(privatecloud, "Private Cloud")

    Business_Service(publiccloud, "Public Cloud Platform",true){
        Application_Service(Application_D, "Application D")
        Application_Component(Software_Component_F, "Software Component F")

    }
    
}

@enduml
```

**Comment by jmanteau** [comment]
@ebbypeter : do you want me to create a PR to fix this ?

**Comment by Potherca** [comment]
Hi! Apologies for not responding sooner. If you have the time/energy to open a merge request, that would be awesome!

I'll keep an eye on the GH notifications to make sure it gets merged a.s.a.p.

**Comment by jmanteau** [comment]
Thanks ! PR created. It was not an emergency as I have used my local fork meanwhile.
