### ISSUE TITLE
Technology Process - Missing Sprite

### ISSUE THREAD

**Issue by zimchaa** [plantuml-stdlib/Archimate-PlantUML#5]
The ``technology-process`` while a valid Archimate item doesn't exist as a valid sprite, per this diagram (``listsprite``): 

![listsprite](https://user-images.githubusercontent.com/1307363/54602876-c37fc500-4a3a-11e9-9a38-0e67e7f1e19b.png)

It's possible to use ``process`` however to recreate a valid looking entity:

![Working Technology Sprite](https://user-images.githubusercontent.com/1307363/54603003-2709f280-4a3b-11e9-9fcf-979fab64fb25.png)

PlantUML code: 

```
@startuml
!includeurl https://raw.githubusercontent.com/ebbypeter/Archimate-PlantUML/master/Archimate.puml

title Archimate Overview

'LAYOUT_AS_SKETCH
'LAYOUT_LEFT_RIGHT
'LAYOUT_TOP_DOWN

Grouping(B_Group,"Business"){
        Business_Process(BProcess, "Business Process")
}

Grouping(T_Group, "Technology"){

    Technology_Process(TProcess, "Technology Process")
archimate #TECHNOLOGY "Working Technology Process" <<process>>
archimate #TECHNOLOGY "Non-Working Technology Process" <<technology-process>>

}
@enduml
```

It could be addressed by a simple change in the include define for that macro, (line 104) from:
```
!define Technology_Process(e_alias, e_label) archimate #TECHNOLOGY "e_label" <<technology-process>> as e_alias
```
to:
```
!define Technology_Process(e_alias, e_label) archimate #TECHNOLOGY "e_label" <<process>> as e_alias
```

I know it doesn't _look_ as nice, but it would fix an error in one of your samples - https://github.com/ebbypeter/Archimate-PlantUML/blob/master/samples/Archimate-Overview.wsd without need to change the code in that sample however.

**Comment by smeagol74** [comment]
I just submitted a pull request to plantuml that fixes some missed icons and colors for archimate https://github.com/plantuml/plantuml/pull/205 so if it will be merged this issue will be fixed authomatically.

**Comment by Potherca** [comment]
@smeagol74 https://github.com/plantuml/plantuml/pull/205 has been merged, is it okay to close this issue?
